@baseUrl = http://localhost:3000

### GET Allies
GET {{baseUrl}}/alliances/allies/1

### GET Invitations
GET {{baseUrl}}/alliances/invitations/1

### Add Ally
POST http://localhost:3000/alliances/5
Content-Type: application/json

{
    "allyToBeAdded": "admin"
}

### Remove Ally
DELETE http://localhost:3000/alliances/1
Content-Type: application/json

{
    "allyToBeRemoved": "Alice94"
}
