@baseUrl = http://localhost:3000

### GET Allies
GET {{baseUrl}}/alliances/allies/1

### GET Invitations
GET {{baseUrl}}/alliances/invitations/1

### Add Ally
POST {{baseUrl}}/alliances/1
Content-Type: application/json

{
    "allyToBeAdded": "Alice94"
}

### Remove Ally
DELETE {{baseUrl}}/alliances/1/Alice94

### Accept invitation
PUT {{baseUrl}}/alliances/2/admin?action=accept

### Reject invitation
PUT {{baseUrl}}/alliances/2/admin?action=reject

