@baseUrl = http://localhost:3000/scores

### GET score by ID
GET {{baseUrl}}/lastLevel/1

### GET all best scores
GET {{baseUrl}}/bestScores/1

### GET friends best scores
GET {{baseUrl}}/friendsBestScores/1/1

### Add Score
POST {{baseUrl}}/addScore
Content-Type: application/json
    
{
    "playerId": "1",
    "score": "15",
    "levelId": "1"
}
